import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

WIDTH, HEIGHT = 1280, 720
FPS = 60
TITLE = "12 Apostelen"

# Player
PLAYER_SPEED = 260
PLAYER_SCALE = 0.75
PLAYER_ANIMATION_SPEED = 10
PLAYER_HEALTH = 100

# Gun / bullets
BULLET_SPEED = 650
BULLET_COOLDOWN = 700

# Enemies
ENEMY_SPEED = 120
ENEMY_DAMAGE = 25
ENEMY_ANIMATION_SPEED = 6

